[project]
name = "CryptoClusters"
version = "0.1.0"
description = ""
authors = [
    {name = "Paweł Solarczyk",email = ""},
    {name = "Hubert Zedlewski",email = ""},
    {name = "Lukas Chmarzynski",email = ""},
    {name = "Robert Dubiela",email = ""},
    {name = "Martyna Kwiatkowska",email = ""},
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-api-python-client>=2.193.0",
    "google-auth",
    "google-auth-httplib2",
    "google-auth-oauthlib",
    "websocket",
    "websocket-client",
    "pandas",
    "numpy",
]